name: SimonPhoto
favicon: null
layout_spectrum: 1
typography_spectrum: 0.50085
title: Simon Thomson Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#212224'
    - '#58534f'
    - '#a0a5a9'
    - '#8d7972'
  brandStrength: 0.3941420048940927
  lightness: 0.3149855087976903
  saturation: 0.05223001283593476
  rhythmicContrast: 0.5335030737333
purpose: []
