name: SimonPhoto
favicon: null
layout_spectrum: 1
typography_spectrum: 0.50085
title: Simon Thomson Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#63473c'
    - '#14150f'
    - '#d3d6e7'
    - '#9ac664'
    - '#62892c'
  brandStrength: 1
  lightness: 0.3125
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
